### ISSUE TITLE
Package cuda-cudnn should be rebuild for cuda 12

### ISSUE THREAD

**Issue by imsedgar** [negativo17/cuda-cudnn#2]
dnf upgrade has package conflicts.
Package `cuda-cudnn` should be rebuild against cuda 12 to require `libcublas.so.12()(64bit)` instead of `libcublas.so.11()(64bit)`.
```
# LANG=C dnf upgrade
Last metadata expiration check: 1:16:07 ago on Mon Dec 19 17:47:06 2022.
Dependencies resolved.

 Problem 1: package cuda-cudnn-devel-1:8.6.0.163-1.fc37.x86_64 requires libcublas.so.11()(64bit), but none of the providers can be installed
  - package cuda-cudnn-devel-1:8.6.0.163-1.fc37.x86_64 requires libcublasLt.so.11()(64bit), but none of the providers can be installed
  - cannot install both libcublas-1:12.0.1.189-1.fc37.x86_64 and libcublas-1:11.11.3.6-1.fc37.x86_64
  - cannot install the best update candidate for package libcublas-1:11.11.3.6-1.fc37.x86_64
  - cannot install the best update candidate for package cuda-cudnn-devel-1:8.6.0.163-1.fc37.x86_64
 Problem 2: package cuda-cudnn-1:8.6.0.163-1.fc37.x86_64 requires libcublas.so.11()(64bit), but none of the providers can be installed
  - package cuda-cudnn-1:8.6.0.163-1.fc37.x86_64 requires libcublasLt.so.11()(64bit), but none of the providers can be installed
  - cannot install both libcublas-1:12.0.1.189-1.fc37.x86_64 and libcublas-1:11.11.3.6-1.fc37.x86_64
  - package libcublas-devel-1:12.0.1.189-1.fc37.x86_64 requires libcublas.so.12()(64bit), but none of the providers can be installed
  - package libcublas-devel-1:12.0.1.189-1.fc37.x86_64 requires libcublasLt.so.12()(64bit), but none of the providers can be installed
  - package libcublas-devel-1:12.0.1.189-1.fc37.x86_64 requires libnvblas.so.12()(64bit), but none of the providers can be installed
  - package libcublas-devel-1:12.0.1.189-1.fc37.x86_64 requires libcublas(x86-64) = 1:12.0.1.189-1.fc37, but none of the providers can be installed
  - cannot install the best update candidate for package libcublas-devel-1:11.11.3.6-1.fc37.x86_64
  - cannot install the best update candidate for package cuda-cudnn-1:8.6.0.163-1.fc37.x86_64
 Problem 3: problem with installed package cuda-cudnn-devel-1:8.6.0.163-1.fc37.x86_64
  - package cuda-cudnn-devel-1:8.6.0.163-1.fc37.x86_64 requires libcublas.so.11()(64bit), but none of the providers can be installed
  - package cuda-cudnn-devel-1:8.6.0.163-1.fc37.x86_64 requires libcublasLt.so.11()(64bit), but none of the providers can be installed
  - cannot install both libcublas-1:12.0.1.189-1.fc37.x86_64 and libcublas-1:11.11.3.6-1.fc37.x86_64
  - package libcusolver-2:11.4.2.57-1.fc37.x86_64 requires libcublas.so.12()(64bit), but none of the providers can be installed
  - package libcusolver-2:11.4.2.57-1.fc37.x86_64 requires libcublasLt.so.12()(64bit), but none of the providers can be installed
  - package libcusolver-2:11.4.2.57-1.fc37.x86_64 requires libcublas.so.12(libcublas.so.12)(64bit), but none of the providers can be installed
  - package libcusolver-2:11.4.2.57-1.fc37.x86_64 requires libcublasLt.so.12(libcublasLt.so.12)(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package libcusolver-2:11.4.1.48-1.fc37.x86_64
 Problem 4: problem with installed package cuda-cudnn-1:8.6.0.163-1.fc37.x86_64
  - package cuda-cudnn-1:8.6.0.163-1.fc37.x86_64 requires libcublas.so.11()(64bit), but none of the providers can be installed
  - package cuda-cudnn-1:8.6.0.163-1.fc37.x86_64 requires libcublasLt.so.11()(64bit), but none of the providers can be installed
  - cannot install both libcublas-1:12.0.1.189-1.fc37.x86_64 and libcublas-1:11.11.3.6-1.fc37.x86_64
  - package libcusolver-2:11.4.2.57-1.fc37.x86_64 requires libcublas.so.12()(64bit), but none of the providers can be installed
  - package libcusolver-2:11.4.2.57-1.fc37.x86_64 requires libcublasLt.so.12()(64bit), but none of the providers can be installed
  - package libcusolver-2:11.4.2.57-1.fc37.x86_64 requires libcublas.so.12(libcublas.so.12)(64bit), but none of the providers can be installed
  - package libcusolver-2:11.4.2.57-1.fc37.x86_64 requires libcublasLt.so.12(libcublasLt.so.12)(64bit), but none of the providers can be installed
  - package libcusolver-devel-2:11.4.2.57-1.fc37.x86_64 requires libcusolver(x86-64) = 2:11.4.2.57-1.fc37, but none of the providers can be installed
  - cannot install the best update candidate for package libcusolver-devel-2:11.4.1.48-1.fc37.x86_64
======================================================================================================================
 Package                        Architecture        Version                          Repository                  Size
======================================================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 libcublas                      x86_64              1:12.0.1.189-1.fc37              fedora-nvidia              223 M
Skipping packages with broken dependencies:
 libcublas-devel                x86_64              1:12.0.1.189-1.fc37              fedora-nvidia               52 k
 libcusolver                    x86_64              2:11.4.2.57-1.fc37               fedora-nvidia               56 M
 libcusolver-devel              x86_64              2:11.4.2.57-1.fc37               fedora-nvidia              2.2 M

Transaction Summary
======================================================================================================================
Skip  4 Packages

Nothing to do.
Complete!
```

**Comment by scaronni** [comment]
Unfortunately it's not open source, so I can not just "rebuild it". Nvidia must release a version for CUDA 12.

Last version they have released is this one: `cuDNN v8.7.0 (November 28th, 2022), for CUDA 11.x` which still links to the CUDA 11 libraries.

I suggest to not update CUDA until that package is up to date if you need it, CUDA 11 is still in the repository.

I will update it as soon as a new version it's available.

**Comment by imsedgar** [comment]
Thanks for the explanation, and for your work providing Fedora packages of nvidia and cuda software!

**Comment by adatum** [comment]
It took a while, but with CUDA 12 and cuDNN v8.8 available the conflict is now resolved. Thanks for keeping the repo up to date!

**Comment by imsedgar** [comment]
Yes, thanks also from me!

**Comment by scaronni** [comment]
Yeah, sorry I probably missed one release between december and now, but there is no way of being notified of new releases.
